### PR TITLE
tooltip-component

### PR DESCRIPTION
**Pull request by bastantebom**
This component will be for the tooltip component utilizing the Material UI Tooltip

Media:

### CODE REVIEW

**Comment by minh-d** [comment]
@bastantebom How can I test this? Do you have example somewhere?

**Comment by bastantebom** [comment]
> @bastantebom How can I test this? Do you have example somewhere?

@minh-d I have yet to create storybook for this after finishing all bug tickets I'm working on

**Review by marjan-ara — APPROVED** [review]

**Comment by aziinz** [comment]
@bastantebom Is there any testing on my side for this branch?

**Comment by bastantebom** [comment]
> @bastantebom Is there any testing on my side for this branch?

Will still have to create storybook, but not for the near future as we are currently working on a different priority

**Pull request merged**
