### PR TITLE
fix: Trimmed text fix, eslint fix, search input refresh fix

### PR DESCRIPTION
**Pull request by Arun-chaitanya**
**Commit 1**:
When the html text was trimmed and if there were incomplete open tags at the end, html was being shown in the UI.
This is a fix for https://github.com/socious-io/web-app-v2/issues/92

**Before**
Screenshot 2023-08-23 at 2 45 56 PM

**After**
Screenshot 2023-08-23 at 2 47 40 PM

**Commit 2**: Adding eslint-config-react-app for react-app eslint config, and retaining search input after refresh from search params

**Commit: modified input component and fixed input overflow** (https://github.com/socious-io/web-app-v2/pull/91/commits/0a0a0a97542048ed056dfe92ccbc5ee904205651)
Before:
Screenshot 2023-08-24 at 1 03 44 PM

After:
Screenshot 2023-08-24 at 1 03 53 PM

**Config Changes**
I have added aliases config in tsconfig and vite.config and added prettier-plugin-sort-imports for sorting imports in files in prettierrc. (I will these changes to all the files as soon as all the other PRs are merged other than mine.)

### CODE REVIEW

**Comment by Arun-chaitanya** [comment]
@jeyem, @minh-d, @ImanRezasefat  
I have changed Button component and added some custom classes similar to tailwind. If you want to keep it on hold, we can cherry pick the commits and merge them.

**Comment by Arun-chaitanya** [comment]
Hi @jeyem, It is done. I have resolved the conflicts

**Comment by jeyem** [comment]
@Arun-chaitanya please don't extend this branch larger than this If you may for other contributions make separate branches and PRs

**Comment by Arun-chaitanya** [comment]
Hi @jeyem, These many file changes are due to import aliases change. Although I can't create separate PR as my changes ongoing changes are going to be dependent on present changes. But as suggested by you, I will wait for these changes to be merged to create another PR as a follow-up for these changes. Till then, I will keep the further changes in my local.

**Comment by jeyem** [comment]
> Hi @jeyem, These many file changes are due to import aliases change. Although I can't create separate PR as my changes ongoing changes are going to be dependent on present changes. But as suggested by you, I will wait for these changes to be merged to create another PR as a follow-up for these changes. Till then, I will keep the further changes in my local.

@Arun-chaitanya you may take branch from current branch and make separate PRs

**Comment by Arun-chaitanya** [comment]
@jeyem, Perfect. That works!

**Comment by Arun-chaitanya** [comment]
@jeyem , This is the follow-up PR

**Comment by Arun-chaitanya** [comment]
@jeyem @seira-yun, Can you assign me any feature to develop? I am really inspired by the cause and motto of the company and want to contribute functionally too. I will do the architectural improvements parallelly. It will take me around 1-2 weeks to convert the whole repo into a strong front-end architectural codebase.
Thanks.

**Comment by Arun-chaitanya** [comment]
@ImanRezasefat can you assign me any feature development, please?

**Pull request closed without merging**
